# docker-compose.yml

services:
  backend:
    build: . # Build from local Dockerfile
    container_name: bookstore_backend
    ports:
      - '${PORT}:${PORT}' # Dynamic port from .env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      - db
    command: npm run dev
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    container_name: bookstore_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped

volumes:
  postgres_data:
